### ISSUE TITLE
Error when searching for "[": malformed pattern (missing ']')

### ISSUE THREAD

**Issue by Blazeflack** [Jaliborc/CustomSearch-1.0#1]
When calling "Lib:Matches(link, search)" the following error will trigger if search contains the character "[":
`malformed pattern (missing ']')`

Proposed fix:
Disable pattern matching for the :find method used on lines 109 and 136:
`if value:find(tag, nil, true) then`
`if text and self:Clean(text):find(search, nil, true) then`

The same should be done in LibItemSearch-1.2 (sorry for including it here, but there is no issue tracker for LibItemSearch), on line 109:
`if name:find(search, nil, true) then`

**Comment by Jaliborc** [comment]
I'll look into it. Disabling features is not a solution though.

**Comment by Blazeflack** [comment]
I guess that's true. I guess I never really thought anyone needed to be able to include patterns in their search string.

**Comment by Blazeflack** [comment]
I only just now realized that pattern matching is used when using searches like "s:SetName" and stuff like that. I feel silly suggesting to remove that, sorry :P
